name: Extract init_boot/boot/recovery image

on:
    workflow_dispatch:
        inputs:
            fileurl:
                description: 'link of full OxygenOS/ColorOS file'
                required: true
                type: string

env:
    GH_TOKEN: ${{ github.token }}

jobs:
    extracting-boot:
        runs-on: ubuntu-latest
        outputs:
          id: ota-link
        steps:
            - name: Checkout Repository
              uses: actions/checkout@main

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
              
#            - name: Download payload dumper
#              run: |
#                pip install git+https://github.com/5ec1cff/payload-dumper
            
#            - name: Extracting OTA
#              run: |
#                payload_dumper --partitions boot,init_boot,recovery ${{ github.event.inputs.fileurl }}

#            - name: List files in the repository
#              run: |
#                mv output/*.img .
#                ls ${{ github.workspace }}
                                
            - name: Setting up Release name
              run: |  
                 pip install unzip-http
                 unzip_http ${{ github.event.inputs.fileurl }} META-INF/com/android/metadata
                 echo "REL_NAME=$(grep "version_name=" metadata | sed 's/^[^=]*=//')"
                 echo "REL_NAME=$(grep "version_name=" metadata | sed 's/^[^=]*=//')" >> $GITHUB_ENV
                 echo "############## $(echo ${{env.REL_NAME}}) ##############"
                        
#            - name: Creating release
#              run: |
#                REL_NAME="PJD110"
#                gh release create $REL_NAME --title $(echo $REL_NAME) --notes "" boot.img init_boot.img recovery.img 
